### ISSUE TITLE
How to make it work in CUDA 10.1+

### ISSUE THREAD

**Issue by momo1986** [frank-xwang/towards-universal-object-detection#2]
Hello, thanks for sharing.

I finished the library compilation.

Since the library configuration would break other applications. I keep the CUDA as 10.1 which is original version in the server.

It passed the compilation.

However nvcc is 10.1
 nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

Since the C++ code is built on CUDA 10.1 and some python code like ffi is depreciated in high version pytorch.

I have tried two methods:
1. Using pytorch 0.4, it looks like that the pytorch version is lower than CUDA version.
Report the error:
undefined symbol: __cudaRegisterFatBinaryEnd
2. Using pytorch 1.0+, the ffi module is depreciated, thus, it has problem to wrap C++ function.

If I use CUDA 10.1, is there a latest pytorch version to support ffi or is there a code demo to work on pytorch version > 1.0.

Thanks & Regards!

**Comment by frank-xwang** [comment]
Hi, thank you for interest in our work. I am sorry, the current codebase doesn't support cuda10.1. In order to make it work for cuda10.1, you may need to check [this link](https://github.com/jwyang/faster-rcnn.pytorch) for details. This codebase is based on their faster r-cnn implementation on cuda9.0 (an older version). Some changes to make files are required to upgrade it to cuda10.1, you can follow pytorch-1.0 branch of [jwyang's implementation](https://github.com/jwyang/faster-rcnn.pytorch) to make necessary modifications.
